services:
  - type: web
    name: book-recommendation-api
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_book_recommendation.app:create_app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
