from typing import List, Dict, Any
import torch
import numpy as np
import os
from .base import BaseRecommender
from ..neural_architecture import SuperIntelligentTwoTower
from ..config import settings
from ..embeddings import embedding_service

class DeepLearningRecommender(BaseRecommender):
    """
    State-of-the-art Two-Tower Neural Recommender.
    Uses generic embeddings + user history sequence + deep fusion.
    """

    def __init__(self, config: Dict[str, Any] = None):
        super().__init__(config)
        self.model = SuperIntelligentTwoTower()
        self.device = torch.device('cpu') # Use 'cuda' if available
        self._load_weights()
        self.model.eval()

    def _load_weights(self):
        if os.path.exists(settings.MODEL_PATH):
            try:
                self.model.load_state_dict(torch.load(settings.MODEL_PATH, map_location=self.device))
                print(f"[{self.name}] Model weights loaded.")
            except Exception as e:
                print(f"[{self.name}] Failed to load weights: {e}")
        else:
            print(f"[{self.name}] No weights found. Using random init (untrained).")

    async def generate_candidates(self, user_id: int, limit: int = 10, context: Dict = None) -> List[Dict[str, Any]]:
        """
        Generate candidates using Deep Learning Model inference.
        Note: True Two-Tower needs a FAISS index of ITEM VECTORS generated by the Item Tower.
        For this implementation, we simulate scoring a batch of top candidates from other sources
        OR we run an ANN search if we had the item index.
        """
        # For MVP: Re-rank/Score using the model is safer than generation if no index exists.
        # However, to be a 'Candidate Generator', we need an index.
        
        # fallback: return [] if no model training loop exists to populate an index
        # But we can implement the "User Embedding" generation part.
        
        context = context or {}
        history = context.get('history', [])
        interests = context.get('interests', [])
        
        # 1. Prepare Inputs
        # History
        if not history:
             hist_vecs = torch.zeros(1, 1, 384)
        else:
            recent = history[-20:] # Max seq len
            emb = embedding_service.encode(recent)
            hist_vecs = torch.tensor(emb).unsqueeze(0) # (1, Seq, 384)
            
        # Interests
        if not interests:
            int_vecs = torch.zeros(1, 384)
        else:
            emb = embedding_service.encode(interests)
            mean = np.mean(emb, axis=0)
            int_vecs = torch.tensor(mean).unsqueeze(0)
            
        # User ID
        u_id = torch.tensor([min(user_id, 49999)])
        
        # 2. Generate User Vector (Query)
        with torch.no_grad():
            user_embedding = self.model.user_tower(u_id, hist_vecs, int_vecs) # (1, OutputDim)
            
        # 3. Search (Hypothetical - requires Index of Book Tower Vectors)
        # Since we don't have a trained Book Tower Index yet, we will skip
        # generating *new* candidates and instead return an empty list 
        # (or maybe re-rank if we changed the interface).
        
        # To make this useful now: Let's assume we have a small set of "popular" books 
        # and we score them.
        
        return [] # Placeholder until we train the model
